FizzBuzz.WebSite/Models/FizzBuzzModel.cs
// <copyright file="FizzBuzzModel.cs" company="TCS">
// Copyright (C) TCS. All rights reserved. 
// </copyright>

using System.ComponentModel.DataAnnotations;

namespace FizzBuzz.WebSite.Models
{
    public class FizzBuzzModel
    {
        [Required(ErrorMessage = "Please enter a number")]
        [Range(1, 1000, ErrorMessage = "Please enter a valid number between 1 and 1000")]
        public int UserInput { get; set; }

        public PagedList.IPagedList<string> FizzBuzzList { get; set; }
    }
}

FizzBuzz.WebSite/Controllers/FizzBuzzController.cs
// <copyright file="FizzBuzzController.cs" company="TCS">
// Copyright (C) TCS. All rights reserved. 
// </copyright>

using System;
using System.Web.Mvc;
using FizzBuzz.Service;
using FizzBuzz.WebSite.Models;
using PagedList;

namespace FizzBuzz.WebSite.Controllers
{
    /// <summary>
    /// Controller class to render fizzbuzz data in a view
    /// </summary>
    public class FizzBuzzController : Controller
    {
        /// <summary>
        /// Variable holding Grid pagesize
        /// </summary>
        private const int PageSize = 20;

        /// <summary>
        /// Variable holding fizzbuzzservice class
        /// </summary>
        private readonly IFizzBuzzService fizzBuzzService;

        public FizzBuzzController(IFizzBuzzService fizzBuzzService)
        {
            this.fizzBuzzService = fizzBuzzService;
        }


        /// <summary>
        /// Action that renders index page and gets data
        /// </summary>
        [HttpGet]
        public ActionResult Index(string userInput, int? page)
        {
            if (userInput != null)
            {
                ViewBag.UserInput = Convert.ToInt32(userInput);
                var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
                var lstWords = fizzBuzzService.GetFizzBuzzData(Convert.ToInt32(userInput));

                return View("Index",
                    new FizzBuzzModel
                    {
                        FizzBuzzList = lstWords.ToPagedList(pageIndex, PageSize),
                        UserInput = ViewBag.UserInput
                    });
            }

            return View("Index");
        }

     
    }
}

FizzBuzz.WebSite/Views/FizzBuzz/Index.cshtml
@* <copyright file="Index.cshtml" company="TCS">
     Copyright (C) TCS. All rights reserved.
    </copyright>*@

@using PagedList.Mvc
@model  FizzBuzz.WebSite.Models.FizzBuzzModel
@{
    ViewBag.Title = "Home Page";
}

<div>
    @using (Html.BeginForm("Index", "FizzBuzz", FormMethod.Get))
    {
        <label>Enter value between 1 to 1000</label>
        @Html.TextBoxFor(m => m.UserInput)
        @Html.ValidationMessageFor(m => m.UserInput, "", new { @class = "fizzerror" })<br />
        <button id="btnSubmit" type="submit">Submit</button>
        <br />
        <br />
        if (Model != null)
        {
            <div id="data_grid">
                <table>
                    @foreach (var result in Model.FizzBuzzList)
                    {
                        <tr>
                            <td>
                                @{
                                    var wordslist = result.Split(' ');
                                    foreach (var word in wordslist)
                                    {
                                        <span class="@word">@word</span>
                                    }
                                }
                            </td>
                        </tr>
                    }
                </table>
            </div>
            <div id="container" style="margin-left: 20px">
                <div class="pagination" style="margin-left: 400px">
                    Page @(Model.FizzBuzzList.PageCount < Model.FizzBuzzList.PageNumber ? 0 : Model.FizzBuzzList.PageNumber) of @Model.FizzBuzzList.PageCount
                    @Html.PagedListPager(Model.FizzBuzzList, page => Url.Action("Index", "FizzBuzz", new { ViewBag.UserInput, page }))
                </div>
            </div>
        }
    }
</div>

FizzBuzz.WebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>



</body>
</html>